# -*- coding: utf-8 -*-
"""4.TipodecoleccióndeDatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MACbj3g7p2kZ06pTDe6dByxUavSo0nHO
"""

###BRENDA ABRIL CASTAÑEDA FERNÁNDEZ FOLIO: 709RR001
##Ejercicio 1.
##Realizar un programa que inicialice una lista con 10 valores aleatorios (del 1 al 10)
##y posteriormente muestre en pantalla cada elemento de la lista junto con su cuadrado y su cubo.

import random  ##Esto importa el módulo "random", que proporciona funciones para trabajar con números aleatorios.

aleator_numeros = [0] * 10

for i in range(len(aleator_numeros)):
  numero = random.randint(1, 10)  ##Generará los números aleatorios del 1 al 10
  aleator_numeros[i] = numero
  cuadrado = numero ** 2
  cubo = numero ** 3
  print(f"Elemento {i+1}: {numero} - Cuadrado: {cuadrado} - Cubo: {cubo}")

##Ejercicio 2.
##Crea una lista e inicializarla con 5 cadenas de caracteres leídas por teclado.
##Copia los elementos de la lista en otra lista pero en orden inverso, y muestra sus elementos por la pantalla.

cadena1 = []
for i in range(0,5):
    n = input ("Ingrese un texto: ")
    cadena1.append(n)

cadena2 = cadena1[:]
cadena2.reverse()

print(cadena1)
print(cadena2)

##Ejercicio 3.
##Se quiere realizar un programa que lea por teclado las 5 notas obtenidas por un alumno (comprendidas entre 0 y 10).
##A continuación debe mostrar todas las notas, la nota media, la nota más alta que ha sacado y la menor.

from random import randint ##Para generar las notas aleatorias entre un rango (randint)
notas = [randint(0,10) for _ in range(5)]
print(notas)
print(f"La nota media es: {sum(notas)/5}")
print(f"La nota más alta es: {max(notas)}")
print(f"La nota más baja es: {sum(notas)}")

##Ejercicio 4.
##Codifica un programa en Python que nos permita guardar los nombres de los alumnos de una clase y las notas que han obtenido.
##Cada alumno puede tener distinta cantidad de notas.
##Guarda la información en un diccionario cuya claves serán los nombres de los alumnos y los valores serán listados con las notas de cada alumno.
##El programa pedirá el número de alumnos que vamos a introducir, pedirá su nombre e irá pidiendo sus notas hasta que introduzcamos un número negativo.
##Al final el programa nos mostrará la lista de alumnos y la nota media obtenida por cada uno de ellos.
##Nota: si se introduce el nombre de un alumno que ya existe el programa nos dará un error.

def main():
    # Se crea un diccionario para almacenar los nombres y notas de los alumnos
    alumnos_notas = {}

    # Se solicita el número de alumnos
    num_alumnos = int(input("Introduce el número de alumnos: "))

    # Solicita los nombres y notas de los alumnos
    for i in range(num_alumnos):
        nombre = input(f"Introduce el nombre del alumno {i + 1}: ")
        notas = []
        nota = float(input(f"Introduce la nota del alumno {nombre} (-1 para terminar): "))
        while nota >= 0:
            notas.append(nota)
            nota = float(input(f"Introduce otra nota para {nombre} (-1 para terminar): "))
        alumnos_notas[nombre] = notas

    # Se calcula la nota media para cada alumno
    for nombre, notas in alumnos_notas.items():
        nota_media = sum(notas) / len(notas)
        print(f"{nombre}: Nota media = {nota_media:.2f}")

if __name__ == "__main__":
    main()

##Ejercicio 5.
##Crea una tupla con los meses del año,
##pide números al usuario, si el número está entre 1 y la longitud máxima de la tupla, muestra el contenido de esa posición sino muestra un mensaje de error.
##El programa termina cuando el usuario introduce un cero.

meses = ("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")#Se crea la tupla

mes=1
while mes!=0:
        mes = int(input("Dame un número entre 1 y 12: "))
        if(mes>=1 and mes<=12):
                print(meses[mes-1])