# -*- coding: utf-8 -*-
"""5.OperadoresRelacionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFudZUhOSrvHdj4KwmaRvlLYwpakJj5J
"""

###BRENDA ABRIL CASTAÑEDA FERNÁNDEZ FOLIO: 709RR001
#Ejercicio 1
#Programa que imprima si el número es positivo o negativo

print("Ingresa un número para verificar: ")
n = int(input())
if(n>0):
    print("El número ingresado es positivo")
elif(n<0):
    print("El número ingresado es negativo")
else:
    print("El número ingresado es igual 0")

#Ejercicio 2
#Programa que imprima si el número ingresado esta en el rango de 1 a 7.

numero = int(input("Ingrese un número: "))
if 1 <= numero <= 7:
    print("Correcto")
else:
    print("Incorrecto")

#Ejercicio 3
#Programa que calcule el interés de una cantidad si es mayor al 30%, sino informa el importe total

# Pedir al usuario el importe
importe = float(input("Ingrese el importe: "))

# Verificar si el importe es mayor al 30%
if importe > 0.3:
    # Calcular el interés (por ejemplo, 10%)
    interes = 0.1 * importe
    # Calcular el importe total
    importe_total = importe + interes
    # Mostrar el interés y el importe total
    print(f"El interés es: {interes}")
    print(f"El importe total es: {importe_total}")
else:
    # Informar el importe total
    print(f"El importe total es: {importe}")