# -*- coding: utf-8 -*-
"""6_sentenciascondicionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjDualOrpdzzAgvFyvYOVb_Bjp3hQnlq
"""

#Brenda Abril Castañeda Fernández
#Ejercicio 1.
#Realizar un ejemplo de menú, donde podemos escoger las distintas opciones hasta que seleccionamos la opción de “Salir”.
def mostrar_menu():
    print("Menú de opciones")
    print("1. Hamburguesa")
    print("2. Alitas")
    print("3. Pizza")
    print("4. Salir")

def opcion_hamburguesa():
    print("Has seleccionado Hamburguesa")

def opcion_alitas():
    print("Has seleccionado Alitas")

def opcion_pizza():
    print("Has seleccionado Pizza")

def main():
    while True:
        mostrar_menu()
        opcion = input("Selecciona una opción: ")

        if opcion == '1':
            opcion_hamburguesa()
        elif opcion == '2':
            opcion_alitas()
        elif opcion == '3':
            opcion_pizza()
        elif opcion == '4':
            print("Saliendo del programa...")
            break
        else:
            print("Opción no válida, por favor intenta de nuevo.")

if __name__ == "__main__":
    main()

#Ejercicio 2.
#Mostrar en pantalla los N primeros número primos. Se pide por teclado la cantidad de números primos que queremos mostrar.

def es_primo(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

def generar_primos(cantidad):
    primos = []
    num = 2
    while len(primos) < cantidad:
        if es_primo(num):
            primos.append(num)
        num += 1
    return primos

# Solicitar al usuario la cantidad de números primos que quiere mostrar
cantidad_primos = int(input("Introduce la cantidad de números primos que quieres mostrar: "))
primos = generar_primos(cantidad_primos)
print(f"Los primeros {cantidad_primos} números primos son: {primos}")

#Ejercicio 3.
#Una persona adquirió un producto para pagar en 20 meses. El primer mes pagó 10 €, el segundo 20 €, el tercero 40 € y así sucesivamente.
#Realizar un algoritmo para determinar cuánto debe pagar mensualmente y el total de lo que pagó después de los 20 meses.

meses = 20
pago_inicial = 10
total_pagado = 0

# Calcula y muestra el pago mensual y el total pagado
for mes in range(1, meses + 1):
    pago_mensual = pago_inicial * (2 ** (mes - 1))
    total_pagado += pago_mensual
    print(f"Mes {mes}: {pago_mensual} €")

print(f"Total pagado después de {meses} meses: {total_pagado} €")

#Ejercicio 4.
#Crea una aplicación que pida un número y calcule su factorial
#(El factorial de un número es el producto de todos los enteros entre 1 y el propio número y se representa por el número seguido de un signo de exclamación.
#Por ejemplo 5! = 1x2x3x4x5=120).

def calcular_factorial(numero):
    if numero == 0 or numero == 1:
        return 1
    factorial = 1
    for i in range(2, numero + 1):
        factorial *= i
    return factorial

# Solicita al usuario un número
numero = int(input("Introduce un número para calcular su factorial: "))

# Calcula el factorial
factorial = calcular_factorial(numero)

# Muestra el resultado
print(f"El factorial de {numero} es: {factorial}")