# -*- coding: utf-8 -*-
"""8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_JpIeXq3f4HcKhn_AcoHZxLucKrYy_C
"""

#Brenda Abril Castañeda Fernández FOLIO: 709RR001
#Ejercicio 1. (2 puntos) Escribe un programa Python que pida un número por teclado y que cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.

import math

# Solicitar un número al usuario
numero = int(input("Introduce un número: "))

# Crear el diccionario con claves desde 1 hasta el número ingresado
# y valores como los cubos de las claves utilizando math.pow
cubos = {i: int(math.pow(i, 2)) for i in range(1, numero + 1)}

# Mostrar el diccionario resultante
print(cubos)

#Ejercicio 2. (2 puntos) Escribe un programa que lea una cadena y devuelva un diccionario con la cantidad de apariciones de cada carácter en la cadena.

# Solicitar una cadena al usuario
cadena = input("Introduce una cadena: ")

# Crear un diccionario para contar las apariciones de cada carácter
conteo_caracteres = {}

# Contar las apariciones de cada carácter en la cadena
for caracter in cadena:
    if caracter in conteo_caracteres:
        conteo_caracteres[caracter] += 1
    else:
        conteo_caracteres[caracter] = 1

# Mostrar el diccionario resultante
print(conteo_caracteres)

#Ejercicio 3. (2 puntos) Vamos a crear un programa en Python donde vamos a declarar un diccionario para guardar los precios de las distintas frutas. El programa pedirá el nombre de la fruta y la cantidad que se ha vendido y nos mostrará el precio final de la fruta a partir de los datos guardados en el diccionario. Si la fruta no existe nos dará un error. Tras cada consulta el programa nos preguntará si queremos hacer otra consulta.

# Declarar un diccionario con los precios de las frutas
precios_frutas = {
    "manzana": 1.2,
    "banana": 0.5,
    "naranja": 0.75,
    "pera": 1.0,
    "uva": 2.0
}

# Función para consultar el precio de una fruta
def consultar_precio():
    fruta = input("Introduce el nombre de la fruta: ").lower()
    if fruta in precios_frutas:
        cantidad = float(input("Introduce la cantidad vendida (en kg o unidades): "))
        precio_total = precios_frutas[fruta] * cantidad
        print(f"El precio total por {cantidad} de {fruta} es: ${precio_total:.2f}")
    else:
        print("Error: La fruta no existe en la base de datos.")

# Bucle para realizar múltiples consultas
while True:
    consultar_precio()
    otra_consulta = input("¿Quieres hacer otra consulta? (s/n): ").lower()
    if otra_consulta != 's':
        break

print("Gracias por usar el programa.")