# -*- coding: utf-8 -*-
"""9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDsg-ItXzFA1HfJM8fboJKfQCb7niMNt
"""

##Brenda Abril Castañeda Fernández Folio: 709RR001
#Ejercicio 1. (1.5 puntos) Realice un programa que pregunte aleatoriamente una multiplicación. El programa debe indicar si la respuesta ha sido correcta o no (en caso que la respuesta sea incorrecta el programa debe indicar cuál es la correcta). El programa preguntará 10 multiplicaciones, y al finalizar mostrará el número de aciertos.

import random

# Función para generar una multiplicación aleatoria y verificar la respuesta del usuario
def pregunta_multiplicacion():
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    respuesta_correcta = num1 * num2
    print(f"¿Cuánto es {num1} x {num2}?")
    respuesta_usuario = int(input("Tu respuesta: "))

    if respuesta_usuario == respuesta_correcta:
        print("¡Correcto!")
        return True
    else:
        print(f"Incorrecto. La respuesta correcta es {respuesta_correcta}.")
        return False

# Contador de aciertos
aciertos = 0

# Preguntar 10 multiplicaciones
for _ in range(10):
    if pregunta_multiplicacion():
        aciertos += 1

# Mostrar el número de aciertos al finalizar
print(f"Has tenido {aciertos} aciertos de 10 preguntas.")

#Ejercicio 2. (1.5 puntos) Obtener el cuadrado de todos los elementos en la lista.
#Lista: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

import math

# Lista de elementos
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Obtener el cuadrado de cada elemento en la lista utilizando math.pow
cuadrados = [int(math.pow(x, 2)) for x in lista]

# Mostrar la lista resultante
print(cuadrados)

#Ejercicio 3. (1.5 puntos) Obtener la cantidad de elementos mayores a 5 en la tupla.
#tupla = (5, 2, 6, 7, 8, 10, 77, 55, 2, 1, 30, 4, 2, 3)

# Tupla de elementos
tupla = (5, 2, 6, 7, 8, 10, 77, 55, 2, 1, 30, 4, 2, 3)

# Obtener la cantidad de elementos mayores a 5
cantidad_mayores_5 = len([x for x in tupla if x > 5])

# Mostrar el resultado
print(f"La cantidad de elementos mayores a 5 es: {cantidad_mayores_5}")

#Ejercicio 4. (1.5 puntos) Obtener la suma de todos los elementos en la lista.

# Definir una nueva lista de ejemplo
lista = [10, 20, 30, 40, 50]

# Calcular la suma de todos los elementos en la lista
suma = sum(lista)

# Imprimir el resultado
print("La suma de todos los elementos en la lista es:", suma)