# -*- coding: utf-8 -*-
"""Ejercicio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0KEKUXV-assngJd3FrD-CIKzvyLeMJt
"""

###BRENDA ABRIL CASTAÑEDA FERNÁNDEZ FOLIO: 709RR001
#Ejercicio 1
# c = (f -32) x 5/9


def convertir(f):
  c=(f-32)* 5/9
  return c


f = float(input("Ingresa la cantidad de grados fahrenheit: "))
print(f"el resultado de los grados celcius es: {convertir(f)}")

#Ejercicio 2
print("Ingrese el primer número: " )
n1 = float(input())
print("Ingrese el segundo número: ")
n2 = float(input())
#Se hace el cálculo de las operaciones
suma = n1 + n2
resta = n1 - n2
mult = n1 * n2
div = n1 / n2
print("La suma es: ",suma)
print("La diferencia es: ",resta)
print("El producto es: ",mult)
print("el cociente es: ",div)

#Ejercicio 3
ladoa = float(input("Lado A: "))
ladob = float(input("Lado B: "))

area = ladoa * ladob
perimetro = 2*ladoa + 2*ladob

print("El área es: ",area)
print("El perímetro es: ",perimetro)

#Ejercicio 4
n1 =float(input("Ingrese el primer número "))
n2 =float(input("Ingrese el segundo número "))
n3 =float(input("Ingrese el tercer número "))

media = (n1+n2+n3)/3
print("La media es: ",media)